services:
  jupyter_networkx:
    labels:
      - "com.vesoft.scope=ngai"
    image: 'weygu/ngai-jupyter-networkx:0.2.10.2'
    container_name: jupyter_networkx
    restart: always
    ports:
      - '38888:8888'
    volumes:
      - ./:/home/jovyan
    healthcheck:
      test: ["CMD-SHELL", "wget http://127.0.0.1:8888 -O /dev/null --no-http-keep-alive || exit 1"]
      interval: 300s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - weygu_nebulagraph-dd-ext-desktop-extension_nebula-net

networks:
  weygu_nebulagraph-dd-ext-desktop-extension_nebula-net:
    external: true
